export const GENRES = [
  "CGアニメーション",
  "テレビCM",
  "MV",
  "商品・製品紹介",
  "サービス紹介",
  "会社・学校紹介",
  "教育・研修",
  "マニュアル・HowTo",
  "インタビュー",
  "バラエティ",
  "ショートドラマ",
  "Youtubeショート【縦型】",
  "Instagram【縦型】",
  "X【縦型】",
  "Facebook【縦型】",
] as const;

export const SKILLS = [
  "Premiere Pro",
  "After Effects",
  "DaVinci Resolve",
  "Final Cut Pro",
  "モーショングラフィックス",
  "カラーグレーディング",
  "サウンドデザイン",
  "3DCG",
  "ドローン撮影",
  "撮影ディレクション",
] as const;
