import { Creator, PortfolioItem, ServicePackage } from "@/types/database";

export const GENRES = [
  "企業VP",
  "YouTube動画",
  "ミュージックビデオ",
  "ウェディング",
  "広告・CM",
  "SNS動画",
  "アニメーション",
  "ドキュメンタリー",
  "イベント撮影",
  "商品紹介",
] as const;

export const SKILLS = [
  "Premiere Pro",
  "After Effects",
  "DaVinci Resolve",
  "Final Cut Pro",
  "モーショングラフィックス",
  "カラーグレーディング",
  "サウンドデザイン",
  "3DCG",
  "ドローン撮影",
  "撮影ディレクション",
] as const;

export const mockCreators: (Creator & {
  portfolios: PortfolioItem[];
  packages: ServicePackage[];
})[] = [
  {
    id: "1",
    user_id: "u1",
    display_name: "田中 映像",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    bio: "映像制作歴10年。企業VPやミュージックビデオを中心に、年間50本以上の制作実績があります。ストーリー性のある映像で、クライアントのメッセージを的確に伝えます。",
    skills: ["Premiere Pro", "After Effects", "カラーグレーディング", "ドローン撮影"],
    genres: ["企業VP", "ミュージックビデオ", "広告・CM"],
    location: "東京都",
    years_of_experience: 10,
    rating: 4.9,
    review_count: 127,
    is_verified: true,
    created_at: "2024-01-15",
    updated_at: "2024-12-01",
    portfolios: [
      {
        id: "p1",
        creator_id: "1",
        title: "株式会社ABC 企業紹介映像",
        description: "企業の理念と事業内容を3分にまとめた紹介映像",
        video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        video_platform: "youtube",
        thumbnail_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=640&h=360&fit=crop",
        genre: "企業VP",
        tags: ["企業VP", "インタビュー", "ドローン"],
        created_at: "2024-06-01",
      },
    ],
    packages: [
      {
        id: "pkg1",
        creator_id: "1",
        name: "スタンダード",
        description: "企業紹介動画（3分以内）",
        price: 300000,
        delivery_days: 14,
        revisions: 2,
        features: ["企画構成", "撮影1日", "編集", "BGM選定", "修正2回"],
        is_active: true,
      },
      {
        id: "pkg2",
        creator_id: "1",
        name: "プレミアム",
        description: "企業紹介動画（5分以内）+ ショートVer.",
        price: 500000,
        delivery_days: 21,
        revisions: 3,
        features: ["企画構成", "撮影2日", "編集", "BGM・SE", "モーショングラフィックス", "ショートVer.制作", "修正3回"],
        is_active: true,
      },
    ],
  },
  {
    id: "2",
    user_id: "u2",
    display_name: "鈴木 クリエイティブ",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    bio: "YouTube動画編集のスペシャリスト。チャンネル登録者100万人超のYouTuberを複数担当。テンポの良いカット編集とエンタメ性の高い演出が得意です。",
    skills: ["Premiere Pro", "After Effects", "モーショングラフィックス", "サウンドデザイン"],
    genres: ["YouTube動画", "SNS動画", "商品紹介"],
    location: "大阪府",
    years_of_experience: 5,
    rating: 4.8,
    review_count: 89,
    is_verified: true,
    created_at: "2024-03-10",
    updated_at: "2024-11-28",
    portfolios: [
      {
        id: "p2",
        creator_id: "2",
        title: "人気YouTuber コラボ企画動画",
        description: "エンタメ系YouTubeチャンネルのコラボ企画動画編集",
        video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        video_platform: "youtube",
        thumbnail_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=640&h=360&fit=crop",
        genre: "YouTube動画",
        tags: ["YouTube", "エンタメ", "バラエティ"],
        created_at: "2024-08-15",
      },
    ],
    packages: [
      {
        id: "pkg3",
        creator_id: "2",
        name: "ベーシック",
        description: "YouTube動画編集（10分以内）",
        price: 30000,
        delivery_days: 5,
        revisions: 1,
        features: ["カット編集", "テロップ挿入", "BGM", "SE", "サムネイル制作"],
        is_active: true,
      },
      {
        id: "pkg4",
        creator_id: "2",
        name: "プロ",
        description: "YouTube動画編集（20分以内）+ モーション",
        price: 60000,
        delivery_days: 7,
        revisions: 2,
        features: ["カット編集", "テロップ挿入", "BGM", "SE", "モーショングラフィックス", "サムネイル制作", "修正2回"],
        is_active: true,
      },
    ],
  },
  {
    id: "3",
    user_id: "u3",
    display_name: "佐藤 モーション",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    bio: "モーショングラフィックスと3DCGを専門としています。テレビCMやWeb広告の制作実績多数。インパクトのあるビジュアルで訴求力の高い映像を制作します。",
    skills: ["After Effects", "3DCG", "モーショングラフィックス", "DaVinci Resolve"],
    genres: ["広告・CM", "アニメーション", "SNS動画"],
    location: "東京都",
    years_of_experience: 8,
    rating: 4.7,
    review_count: 64,
    is_verified: true,
    created_at: "2024-02-20",
    updated_at: "2024-11-15",
    portfolios: [
      {
        id: "p3",
        creator_id: "3",
        title: "新商品ローンチ Web CM",
        description: "3DCGとモーショングラフィックスを活用した15秒Web CM",
        video_url: "https://vimeo.com/123456789",
        video_platform: "vimeo",
        thumbnail_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=640&h=360&fit=crop",
        genre: "広告・CM",
        tags: ["CM", "3DCG", "モーショングラフィックス"],
        created_at: "2024-09-01",
      },
    ],
    packages: [
      {
        id: "pkg5",
        creator_id: "3",
        name: "モーション ベーシック",
        description: "モーショングラフィックス動画（30秒以内）",
        price: 150000,
        delivery_days: 10,
        revisions: 2,
        features: ["コンセプト設計", "モーション制作", "BGM・SE", "修正2回"],
        is_active: true,
      },
    ],
  },
  {
    id: "4",
    user_id: "u4",
    display_name: "高橋 ウェディング",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    bio: "ウェディングビデオグラファー歴7年。300組以上のカップルの最高の瞬間を映像に残してきました。シネマティックな映像美で感動の1日を形にします。",
    skills: ["Final Cut Pro", "DaVinci Resolve", "カラーグレーディング", "ドローン撮影"],
    genres: ["ウェディング", "イベント撮影", "ドキュメンタリー"],
    location: "神奈川県",
    years_of_experience: 7,
    rating: 4.9,
    review_count: 203,
    is_verified: true,
    created_at: "2024-01-05",
    updated_at: "2024-12-05",
    portfolios: [
      {
        id: "p4",
        creator_id: "4",
        title: "ウェディングハイライト - 海辺の挙式",
        description: "湘南の海を背景にしたリゾートウェディングのハイライト映像",
        video_url: "https://vimeo.com/987654321",
        video_platform: "vimeo",
        thumbnail_url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=640&h=360&fit=crop",
        genre: "ウェディング",
        tags: ["ウェディング", "シネマティック", "ドローン"],
        created_at: "2024-10-15",
      },
    ],
    packages: [
      {
        id: "pkg6",
        creator_id: "4",
        name: "ハイライト",
        description: "挙式当日のハイライト映像（3〜5分）",
        price: 200000,
        delivery_days: 30,
        revisions: 2,
        features: ["挙式当日撮影", "ハイライト編集", "カラーグレーディング", "BGM選定", "修正2回"],
        is_active: true,
      },
      {
        id: "pkg7",
        creator_id: "4",
        name: "フルパッケージ",
        description: "前撮り + 挙式当日 + エンドロール",
        price: 450000,
        delivery_days: 45,
        revisions: 3,
        features: ["前撮り撮影", "挙式当日撮影", "ハイライト映像", "エンドロール", "ドローン撮影", "修正3回"],
        is_active: true,
      },
    ],
  },
  {
    id: "5",
    user_id: "u5",
    display_name: "山田 デジタル",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    bio: "SNS動画マーケティングのプロフェッショナル。TikTok、Instagram Reels、YouTube Shortsに最適化された縦型動画の制作が得意。企業のSNS運用支援も行っています。",
    skills: ["Premiere Pro", "After Effects", "モーショングラフィックス"],
    genres: ["SNS動画", "広告・CM", "商品紹介"],
    location: "福岡県",
    years_of_experience: 3,
    rating: 4.6,
    review_count: 42,
    is_verified: false,
    created_at: "2024-06-01",
    updated_at: "2024-11-20",
    portfolios: [
      {
        id: "p5",
        creator_id: "5",
        title: "アパレルブランド Instagram Reels",
        description: "新作コレクションのSNS向けプロモーション動画",
        video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        video_platform: "youtube",
        thumbnail_url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=640&h=360&fit=crop",
        genre: "SNS動画",
        tags: ["SNS", "Instagram", "ファッション"],
        created_at: "2024-11-01",
      },
    ],
    packages: [
      {
        id: "pkg8",
        creator_id: "5",
        name: "SNS動画 単発",
        description: "縦型ショート動画1本（60秒以内）",
        price: 15000,
        delivery_days: 3,
        revisions: 1,
        features: ["カット編集", "テロップ", "BGM", "フォーマット最適化"],
        is_active: true,
      },
      {
        id: "pkg9",
        creator_id: "5",
        name: "SNS動画 月額",
        description: "月8本のショート動画制作",
        price: 100000,
        delivery_days: 30,
        revisions: 2,
        features: ["月8本制作", "企画提案", "カット編集", "テロップ", "BGM", "投稿スケジュール管理"],
        is_active: true,
      },
    ],
  },
  {
    id: "6",
    user_id: "u6",
    display_name: "伊藤 フィルム",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    bio: "ドキュメンタリー映像作家。社会問題やカルチャーをテーマにした作品を多数手がけています。映画祭での受賞歴あり。企業のブランドムービーも得意です。",
    skills: ["DaVinci Resolve", "Premiere Pro", "カラーグレーディング", "撮影ディレクション"],
    genres: ["ドキュメンタリー", "企業VP", "イベント撮影"],
    location: "京都府",
    years_of_experience: 12,
    rating: 4.8,
    review_count: 31,
    is_verified: true,
    created_at: "2024-04-01",
    updated_at: "2024-10-30",
    portfolios: [
      {
        id: "p6",
        creator_id: "6",
        title: "伝統工芸の未来 - ドキュメンタリー",
        description: "京都の伝統工芸職人に密着したドキュメンタリー短編",
        video_url: "https://vimeo.com/111222333",
        video_platform: "vimeo",
        thumbnail_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=640&h=360&fit=crop",
        genre: "ドキュメンタリー",
        tags: ["ドキュメンタリー", "伝統工芸", "カルチャー"],
        created_at: "2024-07-01",
      },
    ],
    packages: [
      {
        id: "pkg10",
        creator_id: "6",
        name: "ブランドムービー",
        description: "企業ブランドストーリー映像（5分以内）",
        price: 800000,
        delivery_days: 30,
        revisions: 3,
        features: ["企画・構成", "撮影3日", "インタビュー撮影", "編集", "カラーグレーディング", "ナレーション", "修正3回"],
        is_active: true,
      },
    ],
  },
];
